//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.net_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employees
    {
        public int Id { get; set; }
        public string Name_Of_Country { get; set; }
        public string FIO { get; set; }
        public string Position { get; set; }
        public string Phone { get; set; }
        public int EmployerId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> TourId { get; set; }
        public string Email { get; set; }
        public System.DateTime Date_Of_Employment { get; set; }
    }
}
