//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.net_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Гостиницы_для_тура
    {
        public int HotelBookId { get; set; }
        public int HotelId { get; set; }
        public int TourId { get; set; }
    
        public virtual Гостиницы Гостиницы { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
