//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.net_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещеннные_города
    {
        public int VistedCityId { get; set; }
        public int CityId { get; set; }
        public int TourId { get; set; }
        public System.DateTime DateOfVisit { get; set; }
    
        public virtual Города Города { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
