//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.net_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники_привязаныне_к_странам__турам
    {
        public int Id { get; set; }
        public int EmployerId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> TourId { get; set; }
    
        public virtual Работники_турагентства Работники_турагентства { get; set; }
        public virtual Страны Страны { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
